### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 204 (Still API works)

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-api#23]
SyntaxError: Unexpected token
 in JSON at position 204
    at Object.parse (native)
    at parse (/opt/sensecity-api/node_modules/body-parser/lib/types/json.js:88:17)
    at /opt/sensecity-api/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:3                  08:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
SyntaxError: Unexpected token
 in JSON at position 204
    at Object.parse (native)
    at parse (/opt/sensecity-api/node_modules/body-parser/lib/types/json.js:88:17)
    at /opt/sensecity-api/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/opt/sensecity-api/node_modules/body-parser/node_modules/raw-body/index.js:3                  08:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ctranoris** [comment]
I had also opened the access log


::ffff:62.38.146.189 - - [28/Apr/2017:09:06:16 +0000] "OPTIONS /api/1.0/is_activate_user HTTP/1.1" 200 4 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:16 +0000] "POST /api/1.0/is_activate_user HTTP/1.1" 200 43 "http://patras.sense.city/scwebsubmit.html" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:18 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:19 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:21 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:24 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:24 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:24 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:26 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:26 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:26 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
::ffff:62.38.146.189 - - [28/Apr/2017:09:06:26 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"

**Comment by ctranoris** [comment]
this is from ::ffff:62.38.146.189 - - [28/Apr/2017:09:17:50 +0000] "OPTIONS /api/1.0/issue/ HTTP/1.1" 200 13 "http://patras.sense.city/scwebsubmit.html" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
